# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://davanstrien.github.io/nnanno/"

git_url = "https://github.com/davanstrien/nnanno/tree/master/"

def custom_doc_links(name): return None
